services:
  mongo:
    image: mongo:6.0.5-jammy
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - type: tmpfs
        target: /data/db

  mongo-express:
    depends_on:
      - mongo
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/

  api:
    profiles:
      - app
    depends_on:
      - mongo
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    command:
      - "--reload"
    ports:
      - "8000:8000"
    volumes:
      - ./app:/backend/app
    environment:
      WATCHFILES_FORCE_POLLING: true
      MONGODB_URL: mongodb://root:example@mongo:27017/
